### ISSUE TITLE
Program crashes when trying to encrypt a folder

### ISSUE THREAD

**Issue by mrerro** [annndruha/SecurePhotos#1]
**Expect** the program to encrypt or decrypt all unencrypted photos in this folder.
[2022-07-25 10-12-43.webm](https://user-images.githubusercontent.com/13213573/180744294-c963082b-1fc4-47f3-9062-5cbb5eb4389a.webm)
Output:

> (.venv) PS D:\NoWork\Other\SecurePhotos> & d:/NoWork/Other/SecurePhotos/.venv/Scripts/python.exe d:/NoWork/Other/SecurePhotos/main.py
> Traceback (most recent call last):
>   File "d:\NoWork\Other\SecurePhotos\src\mainwindow.py", line 116, in _crypt
>     encrypt_file(path, self.cipher)
>   File "d:\NoWork\Other\SecurePhotos\src\aes.py", line 84, in encrypt_file
>     file_bytes = read_file(path)
>   File "d:\NoWork\Other\SecurePhotos\src\aes.py", line 73, in read_file
>     with open(path, 'rb') as f:
> PermissionError: [Errno 13] Permission denied: 'D:/_Tools/_board_systems/board_computer_2_3te10mk\\raw_iamges'

**Comment by annndruha** [comment]
Пока пофиксил тем, что не позволяю пользователю шифровать папки.
Потенциально можно сделать рекурсивное шифрование файлов в папке или архивирование и шифрование.
