### ISSUE TITLE
Иногда изображения отображаются повернутыми, найти причину

### ISSUE THREAD

**Issue by annndruha** [annndruha/SecurePhotos#12]

**Comment by mrerro** [comment]
Посмотри в сторону метоинфы в фото. Встречал такое что фото может быть например повернуто вертикально и в метоинфе содержать - меня надо смотреть повернув на -180. И многие просмоторшики показывают фото корректно - хотя как файл оно выглядит не так.

**Comment by annndruha** [comment]
> Посмотри в сторону метоинфы в фото. Встречал такое что фото может быть например повернуто вертикально и в метоинфе содержать - меня надо смотреть повернув на -180. И многие просмоторшики показывают фото корректно - хотя как файл оно выглядит не так.

Да, дело было действительно в метадате. Открываю изображения теперь через более умный класс -- QImageReader
