### ISSUE TITLE
'NoneType' object has no attribute 'full_path'

### ISSUE THREAD

**Issue by grigoriev-semyon** [annndruha/SecurePhotos#4]
Если приложение запущено и при первом запросе а папку нажато cancel(типа потом выберу папку) при вводе пароля падает 
`Traceback (most recent call last):
  File "/Users/semyon/PycharmProjects/SecurePhotos/src/mainwindow.py", line 85, in _apply_key
    self._select_item()
  File "/Users/semyon/PycharmProjects/SecurePhotos/src/mainwindow.py", line 172, in _select_item
    path = self.ui.treeWidget.currentItem().full_path
AttributeError: 'NoneType' object has no attribute 'full_path'`

**Comment by grigoriev-semyon** [comment]
убрал соответствующие методы которые вызывали ошибку

**Comment by annndruha** [comment]
Пофиксил
