### ISSUE TITLE
fullscreen не меняется если вручную тыкнуть на окошке а не в приложении 

### ISSUE THREAD

**Issue by grigoriev-semyon** [annndruha/SecurePhotos#8]

**Comment by grigoriev-semyon** [comment]
предлагаю убрать вообще функцию fullscreen как доп кнопку
как по мне - лишнее поле, код, который выполняет то же самое, что и обычная кнопка "полный экран" на винде/линуксе

**Comment by annndruha** [comment]
@semen603089 Выпустил релиз 1.0.0! 🎉

Добавил полноценный человеческий фуллскрин
